### ISSUE TITLE
Inline Docs

### ISSUE THREAD

**Issue by DavidCramer** [Desertsnowman/facetwp-manipulator#1]
Pull docs and sample code from facetwp.com via the wp-json api.

**Comment by DavidCramer** [comment]
@mgibbs189 - I got it pulling the docs from the wp-json api, however the shortcodes are not rendering. could you possible take a look at how to make those work?

![](https://cl.ly/2N1S263J3v3n/Image%202016-12-13%20at%207.54.26%20AM.png)

**Comment by mgibbs189** [comment]
Fixed, closing 😄
